### PR TITLE
Skeleton Classes for User, Manager, Employee, and Team.

### PR DESCRIPTION
**Pull request by OmarRammah**
Created skeleton classes for User, Manager, Employee, and Team. The classes have instance variables, but no methods are implemented yet.

### CODE REVIEW

**Review by daryl-tham — APPROVED** [review]
Looks good!

**Review by sarahhe25 — APPROVED** [review]
Looks good! Can add documentation in the next pull request

**Comment by AnonymousTechnologist** [comment]
Framework appears functional, next step is to add methods and interlink the users with the team and ensure functionality with login.

**Review by AnonymousTechnologist — APPROVED** [review]
Framework appears functional, next step is to add methods and interlink the users with the team and ensure functionality with login.

**Pull request merged**
