### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by OmarRammah**
Updated documentation in Schedule classes, and fixed documentation in UI classes.

Fixed branch conflicts.

### CODE REVIEW

**Review by sarahhe25 — APPROVED** [review]
Documentation looks good

**Review by sarahhe25 — CHANGES_REQUESTED** [review]
since this changes schedule classes, might have conflicts with PR #49.

**Comment by daryl-tham** [comment]
I have already added my own documentation to the Schedule classes. See #49

**Review by AnonymousTechnologist — CHANGES_REQUESTED** [review]
This deletes ScheduleGenerator which is called in the Manager UI which would break the functionality completely

**Comment by samreengill88** [comment]
Looks good!

**Pull request closed without merging**
