### PR TITLE
Schedule GUI

### PR DESCRIPTION
**Pull request by daryl-tham**
Added GUI for generating Schedule in Manager portal (No functionality yet except for invalid date format).

### CODE REVIEW

**Comment by daryl-tham** [comment]
Further elaboration on Schedule algorithms (Just need to connect with Team and working hours implementation once finalized). Also tidied up ScheduleGUI.

**Review by AnonymousTechnologist — APPROVED** [review]
Looks good, be wary of deleting imports because of dependencies though

**Review by arandaaron04 — APPROVED** [review]
schedule looks good, generated proper with team, manager and employee.

**Comment by daryl-tham** [comment]
No longer relevant with new GUI, check new pull request

**Pull request closed without merging**
