### PR TITLE
Employee form

### PR DESCRIPTION
**Pull request by samreengill88**
Employee form is updated! It also creates code for others that was accidentally deleted

### CODE REVIEW

**Review by OmarRammah — DISMISSED** [review]
Looks good. Maybe think about making your in-code comments a little more specific to make them easier to understand.

**Review by sarahhe25 — DISMISSED** [review]
This looks good. A next step can be developing test cases and checking for clean architecture.

**Comment by AnonymousTechnologist** [comment]
Seems clean, let's try to do some testing to make sure we don't have any weird edge cases missed.

**Review by AnonymousTechnologist — APPROVED** [review]
Looks good, need to make employee sign up form and then create and run test cases

**Review by arandaaron04 — APPROVED** [review]
make an availability / time off request, otherwise this works

**Review by daryl-tham — APPROVED** [review]
Looks good. Can add compatibility with Schedule and write some test cases

**Pull request merged**
