### PR TITLE
Schedule classes and GUI elements

### PR DESCRIPTION
**Pull request by daryl-tham**
Changed and added the schedule classes and GUI elements to work with new GUI structure.

### CODE REVIEW

**Review by sarahhe25 — APPROVED** [review]
Looks good. Consider pulling out the operations in Schedule() constructor into a separate method for better code organization.

**Comment by daryl-tham** [comment]
Added functionality for Schedule, linking with Payroll timesheet and Time Offs. Modified Time Off GUI and Payroll CSV data reader for compatibility. (Note: Only pushed files I changed, but program will unlikely function without the full implementation of Payroll and TimeOffs)

**Review by OmarRammah — APPROVED** [review]
The code looks good. Instead of just comments however, you should have Javadocs for methods and classes.

**Review by sarahhe25 — CHANGES_REQUESTED** [review]
Integration looks good. A few possible changes:
1. Try not to directly access schedule object from toStrings method, encapsulate schedule and access from a getter instead
2. Can move some code in Schedule() constructor into helper methods to declutter the code, and for SRP
3. Include javadocs for methods and classes

Also, timesheet csv is a temporary database for payroll, and now it's using MySQL. I think it's fine to read the data from csv for now, but will have to integrate later.

**Review by sarahhe25 — APPROVED** [review]
Integration looks good. A few possible changes:

Try not to directly access schedule object from toStrings method, encapsulate schedule and access from a getter instead
Can move some code in Schedule() constructor into helper methods to declutter the code, and for SRP
Include javadocs for methods and classes
Also, timesheet csv is a temporary database for payroll, and now it's using MySQL. I think it's fine to read the data from csv for now, but will have to integrate later.

**Pull request merged**
